### ISSUE TITLE
TraceAnnotator fails when there are no detections present due to IndexError

### ISSUE THREAD

**Issue by mgithinji** [roboflow/supervision#1140]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I am running the [speed estimation code](https://github.com/roboflow/supervision/blob/develop/examples/speed_estimation/inference_example.py) (inference example) on my computer with the `yolov8n-640` model. 

The code runs fine for 11 seconds, while the model detects the cars within the Polygon Zone. But at the 11th second mark, the model fails to make a detection within the Polygon Zone and this breaks the code, because the TraceAnnotator expects a list of detections but the list is empty at that second. So it fails and raises an IndexError. Here's the error warning:

```
Traceback (most recent call last):
  File "/Users/morgangithinji/Workspace/tutorials/speed-camera/speed_camera.py", line 156, in <module>
    annotated_frame = trace_annotator.annotate(
  File "/Users/morgangithinji/Workspace/tutorials/speed-camera/.venv/lib/python3.10/site-packages/supervision/utils/conversion.py", line 21, in wrapper
    return annotate_func(self, scene, *args, **kwargs)
  File "/Users/morgangithinji/Workspace/tutorials/speed-camera/.venv/lib/python3.10/site-packages/supervision/annotators/core.py", line 1300, in annotate
    tracker_id = int(detections.tracker_id[detection_idx])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

To be fair, I'm running the nano model (`yolov8n-640`), so the inaccuracy of this model is causing missed detections when it blips. But even then, the code should still run fine even if there are no detections made for a given second.

Also, in my code, I changed the lines of code from the [inference example code](https://github.com/roboflow/supervision/blob/develop/examples/speed_estimation/inference_example.py):

- 47: `default="yolov8x-640"` -> `default="yolov8n-640"`
- 101: `sv.calculate_dynamic_line_thickness` -> `sv.calculate_optimal_line_thickness`
- 104: `sv.calculate_dynamic_text_scale` -> `sv.calculate_optimal_text_scale`

`dynamic` now causes an error because the function name was changed. You may also want to consider updating the example scripts to reflect this name change in supervision--it's causing errors.

### Environment

python 3.10.14
supervision>=0.20.0
tqdm==4.66.1
requests
ultralytics==8.0.237
super-gradients==3.5.0
inference==0.9.8

### Minimal Reproducible Example

```
python speed_camera.py --source_video_path ./data/vehicles.mp4 --target_video_path ./output/vehicles-output.mp4 --roboflow_api_key $ROBOFLOW_API_KEY
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @mgithinji 👋🏻, we updated this code yesterday. I'll take a look.

**Comment by dvignacioglobal** [comment]
Also having this problem.  I noticed that this happens when there is no person being detected in the video.

`
File "C:\Users\Dennis\miniconda3\envs\PCEE\Lib\site-packages\supervision\detection\tools\smoother.py", line 80, in update_with_detections
    tracker_id = detections.tracker_id[detection_idx]
                 ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
`

**Comment by SkalskiP** [comment]
Hi @mgithinji 👋🏻, I managed to reproduce the bug. I'll do my best to solve this problem.

**Comment by mgithinji** [comment]
Thanks for taking this on @SkalskiP!

**Comment by SkalskiP** [comment]
@mgithinji I did two things:
- updated example code and replaced `sv.calculate_dynamic_line_thickness` and `sv.calculate_dynamic_text_scale` with `sv.calculate_optimal_line_thickness` and `sv.calculate_optimal_text_scale` respectively
- released a new pre-release version `supervision-0.21.0rc1` that at least during my tests worked

could you test it?

```
pip uninstall supervision
pip install supervision==0.21.0rc1
```

**Comment by SkalskiP** [comment]
Wonderful! In that case, I'm closing this issue. For the time being (until `supervision-0.21.0` release) the solution is to run examples with `supervision==0.21.0rc1`.
