### ISSUE TITLE
Error while using custom yolov8 model

### ISSUE THREAD

**Issue by harshalplus1** [roboflow/supervision#365]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

So i imported a pretrined model from the roboflow website itself for a custom object detection. Im using supervision for a counter and opencv for testing on a video. The error happends to be while getting the results from the model. 
This is the code snippet anf on results=model.predict it throws an error
`project = rf.workspace().project("object-detection-s4qwc")
model = project.version(3).model

VIDEO = r"Ctest\test.mp4"

colors = sv.ColorPalette.default()
video_info = sv.VideoInfo.from_video_path(VIDEO)

# extract video frame
generator = sv.get_video_frames_generator(VIDEO)
iterator = iter(generator)

frame = next(iterator)

class_name=["bike", "bus", "car", "motorcycle", "person", "pick up", "skis", "truck"]
# save first frame
cv2.imwrite("first_frame.png", frame)
polygons = [
  np.array([
    [343, 78],[320, 190],[231,311],[70,517],[3,603],[6,716],[405,717],[474,431],[497,242],[453,78]
  ]),
  np.array([
  [457, 80],[538,218],[555,371],[545,555],[521,713],[734,713],[710,471],[669,298],[587,159],[512,75]
  ]),
  np.array([
  [1166, 300],[984, 397],[759, 707],[1084, 709],[1180, 451],[1278, 360]
  ])
]

zones = [
    sv.PolygonZone(
        polygon=polygon,
        frame_resolution_wh=video_info.resolution_wh
    )
    for polygon
    in polygons
]
zone_annotators = [
    sv.PolygonZoneAnnotator(
        zone=zone,
        color=colors.by_idx(index),
        thickness=2,
        text_thickness=4,
        text_scale=2
    )
    for index, zone
    in enumerate(zones)
]
box_annotators = [
    sv.BoxAnnotator(
        color=colors.by_idx(index),
        thickness=1,
        text_thickness=1,
        text_scale=1
        )
    for index
    in range(len(polygons))
]
vid=cv2.VideoCapture(r"testvid\test.mp4")
while True:
    ret,frame=vid.read()
    results = model.predict(frame,confidence=40, overlap=30)[0]
    detections = sv.Detections.from_ultralytics(results)
    for zone, zone_annotator, box_annotator in zip(zones, zone_annotators, box_annotators):
        mask = zone.trigger(detections=detections)
        detections_filtered = detections[mask]
        labels = [
                f"{class_name[class_id]}"
                for _, confidence, class_id, _
                in detections_filtered
            ]
        frame = box_annotator.annotate(
                scene=frame, 
                detections=detections_filtered, 
                labels=labels
            )
        frame = zone_annotator.annotate(scene=frame)
    cv2.imshow("frame",frame)
    if cv2.waitKey(1) and 0xFF==ord("s"):
            break
vid.release()
cv2.destroyAllWindows()
`
This is the error
`Traceback (most recent call last):
  File "c:\project\car_counter_real_time.py", line 69, in <module>
    results = model.predict(frame,confidence=40, overlap=30)[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\LocalCache\local-packages\Python311\site-packages\roboflow\util\prediction.py", line 447, in __getitem__
    return self.predictions[index]
           ~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range`
Can anyone resolve this??

### Additional

_No response_

**Comment by onuralpszr** [comment]
@harshalplus1 hello I see that you try to do predict via "roboflow-python" and 2 things could be problem first is the frame may come empty so check with the "ret" and second is detection actually came "None" because frame may have nothing in the frame as well.  I also suggest you to check "results" what it is returned ? Because if index 0 not exist it is basically empty list or None

**Comment by harshalplus1** [comment]
> @harshalplus1 hello I see that you try to do predict via "roboflow-python" and 2 things could be problem first is the frame may come empty so check with the "ret" and second is detection actually came "None" because frame may have nothing in the frame as well. I also suggest you to check "results" what it is returned ? Because if index 0 not exist it is basically empty list or None

I tried modifying the code according the solution you provided but it still shows the same error
` while True:
    ret,frame=vid.read()
    results = model.predict(frame,confidence=40, overlap=30)[0]
    if ret is not None:
        detections = sv.Detections.from_ultralytics(results)
        for zone, zone_annotator, box_annotator in zip(zones, zone_annotators, box_annotators):
            mask = zone.trigger(detections=detections)
            detections_filtered = detections[mask]
            labels = [
                    f"{class_name[class_id]}"
                    for _, confidence, class_id, _
                    in detections_filtered
                ]
            frame = box_annotator.annotate(
                    scene=frame, 
                    detections=detections_filtered, 
                    labels=labels
                )
            frame = zone_annotator.annotate(scene=frame)
    cv2.imshow("frame",frame)
    if cv2.waitKey(1) and 0xFF==ord("s"):
            break
vid.release()
cv2.destroyAllWindows() `

**Comment by onuralpszr** [comment]
@harshalplus1  check first, predict later and secondly what is the output of "results"

    results = model.predict(frame,confidence=40, overlap=30)   <-- no index number 
    
```python
    ....
   
    if ret is not None:
        results = model.predict(frame,confidence=40, overlap=30)[0]
        detections = sv.Detections.from_ultralytics(results)
   ....
```

**Comment by harshalplus1** [comment]
> @harshalplus1 check first, predict later and secondly what is the output of "results"
> 
> ```
> results = model.predict(frame,confidence=40, overlap=30)   <-- show output without index number 
> ```
> 
> ```python
>     ....
>    
>     if ret is not None:
>         results = model.predict(frame,confidence=40, overlap=30)[0]
>         detections = sv.Detections.from_ultralytics(results)
>    ....
> ```

```
Traceback (most recent call last):
  File "c:\Users\car_counter_real_time.py", line 71, in <module>
    detections = sv.Detections.from_ultralytics(results)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hkshi\AppData\Local\Packages\Python311\site-packages\supervision\detection\core.py", line 259, in from_ultralytics
    xyxy=ultralytics_results.boxes.xyxy.cpu().numpy(),
         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PredictionGroup' object has no attribute 'boxes'
```

**Comment by onuralpszr** [comment]
You should use "from_roboflow" instead of from_ultralytics

https://github.com/roboflow/supervision/blob/fa6238dbc4d9cddfc029c4c2cdf1c553dbd6d37a/supervision/detection/core.py#L435

**Comment by onuralpszr** [comment]
Hey friendly ping @harshalplus1  is it solve the problem ? if yes could you please close the issue with comment or If you still have a issue please let us know as well.

**Comment by HamzaFarhan** [comment]
AttributeError: 'dict' object has no attribute 'boxes'
Getting this error when using a simple YOLO model from ultralytics and then sv.Detections.from_ultralytics(det[0])

**Comment by harshalplus1** [comment]
> Hey friendly ping @harshalplus1  is it solve the problem ? if yes could you please close the issue with comment or If you still have a issue please let us know as well.  

Hey sorry for the late reply I got busy with my exams. I figured that if i import the model from roboflow, this error occurs but if i train a yolov8 model from the same dataset from roboflow. This issue doesnt occur and works perfectly fine. Thanks for helping anyways.
