### ISSUE TITLE
May I know where I can download tracking_result.mp4?

### ISSUE THREAD

**Issue by AK51** [roboflow/supervision#679]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

examples/tracking$ python script.py \
--source_weights_path yolov8s.pt \
--source_video_path input.mp4 \
--target_video_path tracking_result.mp4
Traceback (most recent call last):
  File "/media/ak/HD/supervision/supervision/examples/tracking/script.py", line 77, in <module>
    process_video(
  File "/media/ak/HD/supervision/supervision/examples/tracking/script.py", line 22, in process_video
    video_info = sv.VideoInfo.from_video_path(video_path=source_video_path)
  File "/home/ak/anaconda3/envs/supervision/lib/python3.10/site-packages/supervision/utils/video.py", line 48, in from_video_path
    raise Exception(f"Could not open video at {video_path}")
Exception: Could not open video at input.mp4

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AK51** [comment]
I didn't run the setup. :P it is ok.
