### ISSUE TITLE
sv.LineZone.trigger() returns ValueError in supervision 0.18.0rc1

### ISSUE THREAD

**Issue by NickHerrig** [roboflow/supervision#736]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

When I'm attempting to run `sv.LineZone.trigger(detections=tracked_detections)` I'm getting a `ValueError`

### Error

```bash
Traceback (most recent call last):
  File "/Users/nick/bug/test.py", line 42, in <module>
    line_zone.trigger(detections=tracked_detections)
  File "/Users/nick/bug/venv/lib/python3.11/site-packages/supervision/detection/line_counter.py", line 57, in trigger
    for i, (xyxy, _, confidence, class_id, tracker_id) in enumerate(detections):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
```

I can fix the error by editing the supervision package and ignoring the `data` attribute in `sv.Detections.data` in the file "/Users/nick/bug/venv/lib/python3.11/site-packages/supervision/detection/line_counter.py"

### Environment

- Supervision 0.18.0rc1
- OS: MacOS 14.2.1 (23C71)
- Python: Python 3.11.7

### Virtual Environment Setup  and Download Asset Video

```bash
python3 -m venv venv && source venv/bin/activate
pip install supervision=0.18.0rc1 inference tqdm
wget https://media.roboflow.com/supervision/video-examples/vehicles.mp4
```

### Run Python Script
```python
import supervision as sv
from inference.models.utils import get_roboflow_model
from tqdm import tqdm


if __name__ == '__main__':

    # Load the yolov8X model from roboflow inference.
    model = get_roboflow_model('yolov8n-640')

    # get video info from the video path and dynamically generate line thickness and text_scale
    video_info = sv.VideoInfo.from_video_path('vehicles.mp4')
    text_scale = sv.calculate_dynamic_text_scale(video_info.resolution_wh)

    # create a ByteTrack object to track detections.
    byte_tracker = sv.ByteTrack(frame_rate=video_info.fps)

    # get frames iterable from video and loop over them
    frame_generator = sv.get_video_frames_generator('vehicles.mp4')

    start_point = sv.Point(0, video_info.height*(3/4))
    end_point = sv.Point(video_info.width, video_info.height*(3/4))

    line_zone = sv.LineZone(start_point, end_point)
    line_annotator = sv.LineZoneAnnotator(color=sv.Color.green(), text_scale=text_scale, custom_in_text="OUT", custom_out_text="IN")

    # create a video sink context manager to write the annotated frames to.
    with sv.VideoSink(target_path="linezone.mp4", video_info=video_info) as sink:
        for frame in tqdm(frame_generator, total=video_info.total_frames):

            # run inference on the frame
            result = model.infer(frame)[0]

            # convert the detections to a supervision detections object.
            detections = sv.Detections.from_inference(result)

            # update detections with tracker id's
            tracked_detections = byte_tracker.update_with_detections(detections)

            # print(tracked_detections)
            line_zone.trigger(detections=tracked_detections)
            annotated_frame = line_annotator.annotate(frame=frame.copy(), line_counter=line_zone)

            # save the annotated frame to the video sink.
            sink.write_frame(frame=annotated_frame)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @NickHerrig 👋🏻 ! Good catch! This results from a change that we plan to roll out in `supervision==0.18.0`. Let me work on the fix.

**Comment by SkalskiP** [comment]
Hi, @NickHerrig 👋🏻! I just released [`supervision==0.10.0rc2`](https://pypi.org/project/supervision/0.18.0rc2/). Could you try to install it and confirm it solves your issue?

**Comment by NickHerrig** [comment]
Hey @SkalskiP! Thanks for the quick fix. `LineZone.trigger()` now works as expected!

**Comment by SkalskiP** [comment]
@NickHerrig, that's awesome! Exactly what I wanted to hear!
