### ISSUE TITLE
No module name 'supervision', installed supervision==0.18.0 and imported supervision as sv

### ISSUE THREAD

**Issue by shivakarnati** [roboflow/supervision#809]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "/home/shivakrishnakarnati/Documents/Programming/ROS/ros_supervision_obj/install/object_det/lib/object_det/object_det_node", line 33, in <module>
    sys.exit(load_entry_point('object-det==0.0.0', 'console_scripts', 'object_det_node')())
  File "/home/shivakrishnakarnati/Documents/Programming/ROS/ros_supervision_obj/install/object_det/lib/object_det/object_det_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shivakrishnakarnati/Documents/Programming/ROS/ros_supervision_obj/install/object_det/lib/python3.10/site-packages/object_det/object_det_node.py", line 19, in <module>
    import supervision as sv 
ModuleNotFoundError: No module named 'supervision'
[ros2run]: Process exited with failure 1

### Environment

- supervision 0.18.0

### Minimal Reproducible Example

import supervision as sv 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shivakarnati** [comment]
[build_scripts]
executable=/usr/bin/env python3

added these lines setup.cfg, now the issue is solved

**Comment by SkalskiP** [comment]
Hi @shivakarnati 👋🏻 Thanks for your interest in supervision. Could you give us a bit more description? What commands have you executed? What version of Python do you have?

**Comment by SkalskiP** [comment]
@onuralpszr, can you take a look at this?

**Comment by onuralpszr** [comment]
> [build_scripts] executable=/usr/bin/env python3
> 
> added these lines in setup.cfg, now the issue is solved

Where did you add this ? 

Because what I see from logs it is ROS Env. We don't have setup.cfg file. Our package method based on toml file only.

**Comment by shivakarnati** [comment]
Hello @onuralpszr,
I was using ROS environment to build my project, also I used python=3.10 venv to run the python script ( to detect the objects using supervision). 
I had the problem of detecting supervision module, because my default ROS environment was selected instead of venv. Now I have configured it correctly by adding build_scripts, so it's working fine. 

Thank you supervision Team :)

**Comment by onuralpszr** [comment]
> Hello @onuralpszr, I was using ROS environment to build my project, also I used python=3.10 venv to run the python script ( to detect the objects using supervision). I had the problem of detecting supervision module, because my default ROS environment was selected instead of venv. Now I have configured it correctly by adding build_scripts, so it's working fine.
> 
> Thank you supervision Team :)



Awesome thank you for insight and enjoy with Supervision ! :)
